# Generated by Django 4.1.1 on 2022-12-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="img_url",
            field=models.TextField(default="no image"),
        ),
        migrations.AlterField(
            model_name="coffee",
            name="price",
            field=models.CharField(max_length=255),
        ),
    ]
